version: "3.7"

services:
    mariadb:
        # image: adomenech73/azkaban-mariadb:10
        build: mariadb
        restart: always
        ports:
            - "3306:3306"
        environment:
            - MYSQL_USER=azkaban
            - MYSQL_PASSWORD=azkaban
            - MYSQL_DATABASE=azkaban
            - MYSQL_ROOT_PASSWORD=wootwoot

    executor:
        # image: adomenech73/azkaban-executor:3.84.15
        build: azkaban-executor
        restart: always
        links:
            - mariadb

    webserver:
        # image: adomenech73/azkaban-webserver:3.84.15
        build: azkaban-webserver
        restart: always
        ports:
            - "8443:8443"
        links:
            - executor:azkaban-executor
            - mariadb
